baseurl = "/"
copyright = ""
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableEmoji = true
enableGitInfo = false
footnotereturnlinkcontents = "<sup>^</sup>"
googleAnalytics = ""
hasCJKLanguage = false
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 10
removePathAccents = true
theme = "academic"
title = "Florencia Gómez"
[blackfriday]
angledQuotes = false
extensions = ["backslashLineBreak"]
hrefTargetBlank = true
latexDashes = true
[imaging]
anchor = "smart"
quality = 90
resampleFilter = "lanczos"
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]
section = ["HTML", "RSS"]
[taxonomies]
author = "authors"
category = "categories"
publication_type = "publication_types"
tag = "tags"
