address = "Building 1 Room 1, Stanford University, California, 90210, USA"
appointment_url = "https://calendly.com"
date_format = "Jan 2, 2006"
day_night = false
description = ""
diagram = false
docs_section_pager = true
email = "test@example.org"
font = ""
font_size = "m"
gravatar = false
highlight = true
highlight_languages = ["r"]
latitude = "37.4275"
logo = ""
longitude = "-122.1697"
map = 0
map_api_key = ""
math = false
menu_align_right = false
office_hours = "Monday 10:00 to 13:00<br>\n                  Wednesday 09:00 to 10:00"
phone = "888 888 88 88"
plugins_css = []
plugins_js = []
privacy_pack = false
reading_time = true
section_pager = false
sharing = true
sharing_image = ""
theme = "minimal"
time_format = "3:04 PM"
twitter = ""
zoom = 15
[comments]
engine = 0
[comments.commentable]
docs = true
page = true
post = true
project = true
publication = true
talk = true
[comments.disqus]
shortname = ""
show_count = true
[edit_page]
repo_branch = "master"
repo_url = ""
[edit_page.editable]
docs = true
page = false
post = false
[projects]
post_view = 2
publication_view = 2
talk_view = 2
[publications]
citation_style = "apa"
date_format = "January 2006"
[search]
engine = 1
[search.algolia]
api_key = ""
app_id = ""
index_name = ""
show_logo = false
[[contact_links]]
icon = "twitter"
icon_pack = "fab"
link = "https://twitter.com/Twitter"
name = "DM Me"
[[contact_links]]
icon = "skype"
icon_pack = "fab"
link = "skype:echo123?call"
name = "Skype Me"
[[contact_links]]
icon = "keybase"
icon_pack = "fab"
link = "https://keybase.io/"
name = "Chat on Keybase"
[[contact_links]]
icon = "comments"
icon_pack = "fas"
link = "https://discourse.gohugo.io"
name = "Discuss on Forum"
