---
label: blog post
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: date
  type: datetime
  label: Date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- name: tags
  type: tag_list
  default: []
  label: Tags
pages:
- content/project/problem-solving-cycle-project.md
- content/project/alianza-escuela-universidad-en-la-formación-de-educadores.md
- content/project/project-clic-improving-science-learning-by-expanding-inquiry-and-language-skills.md
- content/post/3-months-later.md
- content/post/landing-in-a-new-position.md
