---
label: blog post
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: date
  type: datetime
  label: Date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- name: tags
  type: tag_list
  default: []
  label: Tags
pages:
- content/post/landing-in-a-new-position.md
- content/post/3-months-later.md
